export const SUPABASE_URL = 'https://hwcvicqeboufzjlyxglp.supabase.co';
export const SUPABASE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh3Y3ZpY3FlYm91ZnpqbHl4Z2xwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQ1ODQxNTgsImV4cCI6MjA0MDE2MDE1OH0.pBYnERTYIWZU4pSvl5y4DmtCMdrX2Q5IAvuTqYaLTig';  // Replace with your public key
